### ISSUE TITLE
Suggestion for tackling pen markings?

### ISSUE THREAD

**Issue by KarthikNair1** [mahmoodlab/CLAM#104]
Hi,

First, thanks for this awesome package! I've been applying it to my dataset for a tumor vs normal prediction task, but I notice that pen markings receive very high attention when present. This makes sense, since they usually indicate tumor ROI's. I was wondering if there are any segmentation parameters which could be tweaked to exclude patches with pen markings? 

Alternatively, is there a built-in way to provide my own segmentation mask for each slide and have CLAM use this mask instead of generating one?

Thanks!

**Comment by fedshyvana** [comment]
Hey sorry for the delay, you can certainly use your own masks to tackle pen-markings but it might not be so straightforward.... As you can see under wsi_core/WholeSlideimage, there's functions we call to load in segmentations (in the form of contour coordinates). But if your mask is binary instead of a set of contours, you might have to first convert them (e.g. by calling cv2.find_contours), and then you have to make sure to scale the contour coordinates up if your mask is downsampled relative to the original WSI.  

<img width="878" alt="image" src="https://user-images.githubusercontent.com/39780468/157318986-ede4972f-6c0e-496d-8a0d-6ae32bcf97e2.png">

**Comment by KarthikNair1** [comment]
Hi, thanks for this reply. I ended up implementing this in a similar way to what you suggested and it seems to work :)

Thanks again!
