### ISSUE TITLE
Datasets have changed and want to reproduce same results

### ISSUE THREAD

**Issue by omniaalwazzan** [mahmoodlab/CLAM#108]
Hi Chen
I am glad that there is a well-written code for segmenting histopathology images like CLAM. Thanks for sharing it.
 
I am very interested in integrating histopathology images with gene expression, as proposed in the PROSIS paper. As a result, I've come to inquire about CLAM.

I did run the CLAM code and luckily it worked without errors.

I'd like to replicate the same result in the CLAM paper for at least one of the datasets mentioned. However, datasets such as CAMELYON16/17 and CPTAC have been updated and are now larger than the one used in the CLAM paper.
My concern is that I want to have the same dataset so that I can tell if I configured the CLAM code correctly or not.

So, would you mind sharing any pointers that could help me achieve the same result?

Best regards,
Omnia.

**Comment by fedshyvana** [comment]
i don't think you'll be able to exactly reproduce the same result since the way you segment/patch the tissue will also be different from how we originally processed the data (which unfortunately might not be reproducible since we processed slides using a much older version of the CLAM code before it was cleaned up and released to public). So I would say as long as you get reasonable numbers close to what we reported you should be confident that it's working properly! If you have additional questions/concerns, feel free to shoot me an email.

**Comment by omniaalwazzan** [comment]
I see. 

Thank you so much for your quick response.
