### ISSUE TITLE
Patches considered in Background while patching

### ISSUE THREAD

**Issue by shubhaminnani** [mahmoodlab/CLAM#161]
Hi @fedshyvana ,
I am creating patches from TCGA dataset (GBM cohort), and see that patches have background considered. I am using the same preset as tcga.csv provided in repo.

Sample Images:
TCGA-08-0359-01Z-00-DX1.FBED91D4-4D46-4354-ABCF-3D2EBDA42C6D
![TCGA-08-0359-01Z-00-DX1 FBED91D4-4D46-4354-ABCF-3D2EBDA42C6D](https://user-images.githubusercontent.com/50418503/200396155-f18790bf-a925-4700-bc66-855c715cf0b1.jpg)

TCGA-08-0360-01Z-00-DX1 CE8208FA-E2FA-44C9-9EA7-9DE5278BD217
![TCGA-08-0360-01Z-00-DX1 CE8208FA-E2FA-44C9-9EA7-9DE5278BD217](https://user-images.githubusercontent.com/50418503/200396178-cfc4f38f-94c6-4909-bff0-5a10b008cfe9.jpg)

TCGA-08-0357-01Z-00-DX1 F0E652B4-DE1D-41AA-A531-FEBC41C62D4F
![TCGA-08-0357-01Z-00-DX1 F0E652B4-DE1D-41AA-A531-FEBC41C62D4F](https://user-images.githubusercontent.com/50418503/200396207-acd0e918-6572-46f3-ac5a-498d43fdf063.jpg)

Problem: 
How are this patches handled? Is any other check applied before storing the coordinates? Does this not affect attention to be baised in noise or tissue?

Thanks,
Shubham

**Comment by fedshyvana** [comment]
There are no checks applied before storing coordinates - although in theory we can apply a filtering step when the patches are actually loaded for feature extraction. In the examples you showed here, it may be possible to filter out those irrelevant regions simply by increasing the threshold **sthresh** . In practice we did not find that these extra background region receive any attention in the trained models which makes sense since presumably they're consistently present for all classes in your dataset - if they're somehow only correlated with a single class then you're right that the model may falsely associate their presence with the class label.

**Comment by shubhaminnani** [comment]
Thanks @fedshyvana
