### ISSUE TITLE
I want to use your tumor segmentation pretrained model 

### ISSUE THREAD

**Issue by AnitaGoro** [mahmoodlab/CLAM#203]
Hello, I have a bunch of TCGA endometrial svs files and I want to extract their tumoral region without a pathologist´s annotation. Do you think that I can use your normal-tumor model to do this? If this is the case, how do I do it? I have already cloned the github and installed the libraries. I tried running your first command on the readme file and it worked. 
Thank you very much!!

**Comment by fedshyvana** [comment]
Hi @AnitaGoro, we do not have a tumor vs. normal model to accomplish your task. The toolbox is currently designed to perform WSI-level classification instead of ROI-level classification. For your task description you may need to find tumor vs. normal classifiers trained on ROIs for endometrial cancers, although I am not aware of any off the top of my head.
