### ISSUE TITLE
Image likely too large for successful segmentation, aborting - implemented fix available?

### ISSUE THREAD

**Issue by Fel1xJulian** [mahmoodlab/CLAM#241]
Hi,

I'm encountering the same issue others seem to have had and was wondering, whether there is a readily available fix to avoid scaling down the files. Thank you!

progress: 0.00, 0/1
processing huge5.png
level_dim 102430 x 97408 is likely too large for successful segmentation, aborting
100%|████████████████████████████████████████████| 1/1 [00:00<00:00, 186.85it/s]
average segmentation time in s per slide: 0.0
average patching time in s per slide: 0.0
average stiching time in s per slide: 0.0

**Comment by fedshyvana** [comment]
Is there a reason you need to perform segmentation at level 0? It's basically saying your you're trying to perform segmentation on a image of size 102430 x 97408 into memory which is likely not feasible (unless you have hundreds of GBs of RAM). 

If this is due to your WSIs only having a single pyramid level, then I would suggest converting them to pyramidal tiffs first, using tools like imagemagick or pyvips.

**Comment by Fel1xJulian** [comment]
Thank you for your answer. The reason we want to perform the segmentation on this magnification image is that we work with neurodegenerative disease WSIs with very subtle plaques and the WSIs I have access to were only captured with a high magnification. We do have 1000Gb of RAM available, would that be enough? And if so, how would I need to adapt the code to allow for the segmentation and circumvent the limit?  I tried to find the limit that prevents the process from starting in the code, but to no avail.

**Comment by fedshyvana** [comment]
https://github.com/mahmoodlab/CLAM/blob/206bf2dfddd5a297513087358302c8d9b2233192/create_patches_fp.py#L178
You can try commenting out this block. But tbh, I would still recommend creating tiled pyrarmidal tiffs first because the "segmentation" is just grabbing the tissue contours, it's not trying to segment precise cells/cell boundaries. It should be something that can be done at low magnification and will also be much much faster.

**Comment by Fel1xJulian** [comment]
Thank you for your input. I will heed your advice and try to create pyramidal tiffs from my czi files.
