### ISSUE TITLE
Questions about threshold parameters

### ISSUE THREAD

**Issue by huha149** [mahmoodlab/CLAM#243]
Hi，I want to use the functions isBlackPatch_S and isWhitePatch_S from wsi_utils.py to filter patches when creating patches with create_patches_fp.py. Is this feasible? 
because I noticed that the preset patch_params does not contain related patch threshold parameters.
![image](https://github.com/mahmoodlab/CLAM/assets/147480747/a2f4b1ab-85f6-4fb7-9287-ecb0749c7ef7)

**Comment by fedshyvana** [comment]
Sorry for the late response! You're right this is currently not supported by create_patches_fp.py since the _fp version of the script doesn't actually read any image patches during patching but instead only checks patch coordinates against segmentation contours. If you still want to filter patches further, I would recommend training your own tissue vs. background filter (perhaps you can build it directly on top of pre-extracted embeddings so that little to no additional computational overhead is introduced).
