### ISSUE TITLE
The time that CONCH takes

### ISSUE THREAD

**Issue by TXPsim** [mahmoodlab/CLAM#266]
Thanks for your excellent work!

May I ask the approximate time it takes to extract the features of a WSI using CONCH in a single GPU? Because I noticed that CONCH takes longer to extract features than ResNet50.

I'm looking forward to your reponse. Thank you so much!

**Comment by fedshyvana** [comment]
Hi, I don't have concrete numbers but yes it is expected since CONCH is quite a bit larger than the truncated ResNet50 (for the same reason, UNI is expected take even longer). If the forward pass becomes too much of a bottleneck I think you can try to perform inference in torch autocast fp16 for a pretty significant speed up.

**Comment by TXPsim** [comment]
Thanks for your quick reply！It is very helpful to me and I would like to try your advice!
