### ISSUE TITLE
Proper visualization of the heatmap

### ISSUE THREAD

**Issue by furkandurmus** [mahmoodlab/CLAM#42]
Hi there, I am trying to test a single kidney wsi from TCGA.  I could be able to test my data, however; I m facing some issues with the visualization of the heatmap. My attention score and coords. shapes are respectively : [3, 80560],(80560, 2).
 If I pass the parameters as below I obtain an image but it doesn't make sense as you have shown in your demos. 
Any help would be appreciated, thanks.

        abc = WholeSlideImage("./DATA_DIRECTORY/slide_0.svs")
        heatMap = abc.visHeatmap(A_SCORE, coords)
I called visHeatmap just like this,

![2021-03-19_15-48-02](https://user-images.githubusercontent.com/12261453/111782821-87ea9080-88ca-11eb-8869-ff86e007338c.png)
![2021-03-19_15-37-17](https://user-images.githubusercontent.com/12261453/111782830-89b45400-88ca-11eb-8fa0-ec4fee398159.png)

**Comment by fedshyvana** [comment]
Hi, so since you're using multi-branch CLAM, you can choose to visualize the attention scores corresponding your predicted class (from model), which is Y_hat. So if you index your attention scores by Y_hat, you'll end up a 1 x N vector of scores. Also I see that you're using vis_level = -1, there was actually a small bug in my code so vis_level = -1 was not working properly but I pushed a update already maybe try again after you pull the update and see you get something reasonable (or you can also just try to set vis_level manually, like 2 or 3 or something).
