### ISSUE TITLE
getting mask contours

### ISSUE THREAD

**Issue by gabemarx** [mahmoodlab/CLAM#46]
Hello! 

Thanks again for a fantastic repo, it has proven essential to my work! 

I was wondering if there is an easy way (or if you could recommend which lines to alter) for me to save the contour objects created during the masking process. This would be very handy for getting whole tissue area and using the mask for other parts of my project. 

Best,
Gabe

**Comment by fedshyvana** [comment]
Hi, you can refer to the helper functions of WholeSlideImage class under wsi_core. Specifically:
``` 
def initSegmentation(self, mask_file):
        # load segmentation results from pickle file
        import pickle
        asset_dict = load_pkl(mask_file)
        self.holes_tissue = asset_dict['holes']
        self.contours_tissue = asset_dict['tissue']

def saveSegmentation(self, mask_file):
        # save segmentation results using pickle
        asset_dict = {'holes': self.holes_tissue, 'tissue': self.contours_tissue}
        save_pkl(mask_file, asset_dict)
```
after you do segmentation, you can call saveSegmentation to just pickles the contours objects as a dictionary, and you can load it back in using initSegmentation. Since it's just a pickled dictionary, if you need to use the contours for something else you can just unpickle yourself and access the contours directly.
