### ISSUE TITLE
Performance on CAMELYON17

### ISSUE THREAD

**Issue by lzx325** [mahmoodlab/CLAM#52]
I tried your trained model `camelyon_40x_cv_CLAM_100_s1` on the CAMELYON16+17 dataset. The model could perform very well on the CAMELYON16 subset (AUC: 0.96~0.97) but after adding CAMELYON17, the AUC of CAMELYON16+17 drops to around 0.80, which means that the model prediction is wrong on a lot of slides in CAMELYON17.  I followed your advice to change the pixman version to 0.40 and the patch stitches of CAMELYON17 look OK now. 
Have you experienced this during your experiments? Do you know what is likely the problem? Did you perform some additional pre-processing steps on CAMELYON17? Currently I am using the same settings in
`bwh_biopsy.csv` to segment both CAMELYON16 and CAMELYON17. Thank you if you can help.

**Comment by fedshyvana** [comment]
hi, sorry for the late response. i was busy with a paper deadline. How did you prepare the labels in Camelyon17? Since Camelyon17 challenge was a staging task (where each slide can be itc, micro met, macro met or negative, and staging is done at the patient level) but in our study, we were doing positive vs. negative lymph node classification. Based on the information given in the evaluation page of the challenge (https://camelyon17.grand-challenge.org/Evaluation/), it says "Lymph nodes containing only ITC are therefore not counted as positive lymph nodes". As a result, we treated itc and negative as the negative class and micro/macro-met as the positive class for binary classification.  This might explain differences in performance if you used labels from camelyon17 differently.

**Comment by lzx325** [comment]
Thank you for the clarification. I can now reproduce your results.

**Comment by ParastooSotoudeh** [comment]
Hi,

I am going to work on Camelyon 17 dataset. I was wondering to know if it is possible to have access to a base code for the preprocessing of this dataset for classification task. Could you please help me with this?
