### ISSUE TITLE
Clam_sb 

### ISSUE THREAD

**Issue by mayurmallya** [mahmoodlab/CLAM#56]
Hi fedshyvana, I'm wondering if you could clarify some doubts I have regarding the CLAM_SB model.

I'm working on a 3-class subtyping problem where I try to make use of the slide-level feature vector for subsequent analysis.

1) In the 'Method' section of the paper, I believe you have described the multi-branched attention network (CLAM_MB), which produces N number of slide-level feature vectors (where N is the number of classes). For my case, since I need a single slide-level feature vector, I'm guessing I need to use CLAM_SB right?

2) Secondly, since CLAM_SB would have a single attention branch, I believe there would not be the concept of in-class attention and out-of-class attention, right? Or maybe the single branch is in-class attention? But either way, there would not be any difference between subtyping and grading right? (since in the case of CLAM_MB, for subtyping, the high-attention patches of out-of-class attention branch were used as negative evidence, while in this case, there is no out-of-class attention branch)

Kindly share your thoughts. Thank you!

**Comment by fedshyvana** [comment]
Hi, sorry for the delay I have been incredibly busy with other projects. 
1. You can still use CLAM_MB, but just take the feature vector corresponding to the model's predicted class, but otherwise CLAM_SB works too.
2. I think there is still in-class attention vs. out-class from the perspective of training the instance-level classifiers. Since you still have n instance-level classifiers (where n is the total number of classes), each tasked with distinguishing between class i vs. those not of class i. So while you only have a single attention branch, if your ground truth class is k, then the top attended patches can be considered positive evidence for the instance-level classifier corresponding class k, and considered negative evidence for all other instance-level classifiers.

**Comment by mayurmallya** [comment]
Hi Max,

Quick follow-up question-

> So while you only have a single attention branch, if your ground truth class is k, then the top attended patches can be considered positive evidence for the instance-level classifier corresponding class k, and considered negative evidence for all other instance-level classifiers.

What would be the positive evidence for the out-of-class instance-level classifiers?

Thank you in advance!
