### ISSUE TITLE
Visualizing attention scores on whole slide image

### ISSUE THREAD

**Issue by zaid478** [mahmoodlab/CLAM#6]
Hi,
Thanks for your great work. I trained the model on a new dataset. 
Now, I want to visualize attention scores on the whole slide image. Is there any functionality available in the code itself for this? Or could you recommend me steps to do this?

I want this for interpretability. Any help would be appreciated.

**Comment by fedshyvana** [comment]
Hi Muhammad, it's very easy to get the attention scores for the patches used by the model for prediction, see [here](https://github.com/mahmoodlab/CLAM/issues/2), although you might have to implement a custom script to collect them for your own dataset. In terms of customized visualization such as the ones displayed on the website demo, those involve generating patches using an overlap and the visualization also involves several moving parts, which we had to optimize in order to efficiently deploy the outputs to our website server. It is an ongoing effort on our end to generalize that functionality to a wider array of problems and audience and organize that code into a visualization toolbox that we hope to release in a future update.

**Comment by syedsadiqalinaqvi** [comment]
@fedshyvana regarding your comment above, have you guys released the code for visualization attention scores?

**Comment by fedshyvana** [comment]
Hi, I just recently pushed a major update to the code. heatmap visualization can be handled through the visHeatmap function of the WholeSlideImage class. Once you construct a WSI object, and compute attention scores, you can pass the attention scores, patch coordinates, along with other arguments (see visHeatmap definition for details) to build a heatmap. In the future we might provide a comprehensive streamlined example for how this can be done for an arbitrary dataset, but for now the pieces are there for you to implement your own script if necessary.
