### ISSUE TITLE
Inconsistent Tissue Segmentation

### ISSUE THREAD

**Issue by artemi8** [mahmoodlab/CLAM#61]
Hello, Thank you for making this amazing project a public repo!

I used TCGA-BRCA WSI slides for experimenting with CLAM. When using the default segmentation parameters from the given tcga.csv file I observed some segmented WSIs had white background between the tissue region. I also observed that segmentation improved when I changed **use_otsu** parameter in tcga.csv to **TRUE**. I have attached two examples on both the cases for your reference. 

Can you please point out the segmentation/thresholding parameters that need to be tuned to get more precise segmentation. 

Using default parameters in tcga.csv with **use_otsu = FALSE**
![Tissue issue](https://user-images.githubusercontent.com/41601863/122008195-5f453a80-cdd6-11eb-800a-78b4a6b5d41b.JPG)

Using default parameters in tcga.csv with **use_otsu = TRUE** 
![Tissue issue_2](https://user-images.githubusercontent.com/41601863/122012885-45f2bd00-cddb-11eb-9a90-26aae0fb0310.JPG)

**Comment by fedshyvana** [comment]
Hi, you are welcome to refer to https://github.com/mahmoodlab/CLAM#custom-default-segmentation-parameters if you are interested in achieving really precise segmentation, but otherwise i think for most tasks even if you some how have a bunch of "empty" patches in your bags, the classification model will learn just fine since it should learn to ignore those relevant regions and attend to diagnostically relevant regions.

**Comment by artemi8** [comment]
Okay thank you for your response.
