### ISSUE TITLE
How can I get my own csv file like the camelyon_clean.csv you put in the folder?

### ISSUE THREAD

**Issue by smalldan1022** [mahmoodlab/CLAM#8]
Thanks for the Repository. 
I followed the data pipeline to prepare my own dataset , and got some problem on this step

CUDA_VISIBLE_DEVICES=0,1 python extract_features.py --data_dir DIR_TO_PATCHES --csv_path CSV_FILE_NAME --feat_dir FEATURES_DIRECTORY --batch_size 512

I am not sure if the CSV_FILE_NAME means the process_list_autogen.csv generated by the previous step?

**Comment by fedshyvana** [comment]
Hi Dan, yes feel free to use the autogen csv file if you didn't create any other csv files. The camelyon csv file I put in the folder is meant as an example of how you should organize your dataset (including identifiers and labels) for supervised training. Unfortunately, since everyone has his/her own dataset that is organized differently, you would have to find ways to parse your own dataset to organize them into the specified format that's provided in the example. There are more details about this in the instruction README.
