### ISSUE TITLE
Problem of getting threshold of high/low attention score and create patches problem

### ISSUE THREAD

**Issue by Legendddd** [mahmoodlab/CLAM#95]
# Model was trained using TCGA and GTEx WSIs aiming to localise tumour region. It worked.

Now I am trying to use the model to estimate tumour purity as well as extract all high attention patches but fail to find the good threshold to do so. I want to compare estimate tumour purity with Absolute purity score that generated from SNP6.0 data.

 # Run 1 
Here is my yaml file parameters:
  label_dict:
    normal_tissue: 0
    tumor_tissue: 1
patching_arguments:
  patch_size: 256
  overlap: 0.5
  patch_level: 0
  custom_downsample: 1
model_arguments:
  ckpt_path: /Model_1/heatmaps/ckpts/s_9_checkpoint.pt
  model_type: clam_sb # see utils/eval_utils/
  initiate_fn: initiate_model # see utils/eval_utils/
  model_size: small
  drop_out: true
heatmap_arguments:
  vis_level: -1
  alpha: 0.4
  blank_canvas: false
  save_orig: false
  save_ext: jpg
  use_ref_scores: true
  blur: false
  use_center_shift: true
  use_roi: false
  calc_heatmap: true
  binarize: false
  binary_thresh: -1
  custom_downsample: 1
  cmap: jet
sample_arguments:
  samples:
    - name: "topk_high_attention"
      sample: true
      seed: 1
      k: 15 # save top-k patches
      mode: topk

The output heatmap looks great, but I found the distribution of attention score hard to find a threshold. If I set cut-off = 0, only 10417/44324 is positive.
Attention score was extracted using this code:
 dset = file['attention_scores']
        coord_dset = file['coords']
        scores = dset[:]
        coords = coord_dset[:]
        output = np.concatenate((coords, scores), axis=1)
        output = pd.DataFrame(output, columns=["x", "y", "scores"])

![image](https://user-images.githubusercontent.com/40993128/150079318-aa462799-3d0a-4ccb-b2db-70d30c15188c.png)
![image](https://user-images.githubusercontent.com/40993128/150080276-5f02a74f-742d-420b-850e-d03e17b70523.png)

# Run2
This time I set binarise = T and binary thresh = 0
  binarize: true
  binary_thresh: 0
But the output heatmap looks wried, is it because the  label_dict was set to normal_tissue: 0 tumor_tissue: 1 and scores > binary_thresh were all colored into red? But the distribution of attention score is not.

![image](https://user-images.githubusercontent.com/40993128/150075934-464a1acf-1fc2-4ec7-80e0-135c8e6c81a8.png)
![image](https://user-images.githubusercontent.com/40993128/150078200-3db83a54-37d9-41d2-a278-02b00670e139.png)
![image](https://user-images.githubusercontent.com/40993128/150077698-3f91c424-e408-43ea-b170-17674a81383b.png)

# Create patches problems
Create patches worked well with TCGA svs files, but when I tried to use it on local ndpi files, it didn't work. It seems to identiy whole image as tissue.
![image](https://user-images.githubusercontent.com/40993128/150078728-27ec8241-3730-48a3-9406-88ce51d60cbf.png)

# Is there a better way to save all high attention patches? 
By setting k: 15 will only save 15 top patches for each WSI.

**Comment by fedshyvana** [comment]
Thresholding attention scores is tricky business since it's also relative to patches within a given slide. A few things you can try are:
1. convert them to percentiles within each slide, and pick a percentile as your threshold
2. softmax normalization and use 1/N as threshold
3. don't use the attention scores, but rather, use the instance-classifier output (which is a probably score between 0 to 1), something that Tourniaire et al. did here: https://proceedings.mlr.press/v156/tourniaire21a.html 

for create patches, there's a bunch of templates (via --preset) you can use for different datasets (also feel free to play around with different parameters and create a template that works for you). For the slide you just showed, i think bwh_biopsy.csv should work pretty well (basically you need to increase the threshold, e.g. increase sthresh). 

lastly, i don't have a script dedicated to just saving high attention patches, but once you have computed the attention scores, if you just save their corresponding coordinates, it should be easy enough to just use wsi = openslide.open_slide(path_to_wsi) and wsi.read_region() to read those patches.
